export const ENDPOINTS = {
  AUTH: {
    LOGIN:           '/auth/login',
    REGISTER:        '/auth/register',
    LOGOUT:          '/auth/logout',
    REFRESH:         '/auth/refresh',
    ME:              '/auth/me',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD:  '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
  },
  USERS: {
    LIST:      '/users',
    ME:        '/users/me',
    ME_AVATAR: '/users/me/avatar',
    BY_ID:     (id: string) => `/users/${id}`,
  },
  CUSTOMERS: {
    LIST:   '/customers',
    CREATE: '/customers',
    ME:     '/customers/me',
    BY_ID:  (id: string) => `/customers/${id}`,
  },
  VEHICLES: {
    LIST:        '/vehicles',
    CREATE:      '/vehicles',
    BY_CUSTOMER: (customerId: string) => `/vehicles/customer/${customerId}`,
    BY_ID:       (id: string) => `/vehicles/${id}`,
  },
  SERVICES: {
    LIST:       '/services',
    CATEGORIES: '/services/categories',
    CREATE:     '/services',
    BY_ID:      (id: string) => `/services/${id}`,
  },
  BOOKINGS: {
    LIST:   '/bookings',
    CREATE: '/bookings',
    BY_ID:  (id: string) => `/bookings/${id}`,
    CANCEL: (id: string) => `/bookings/${id}/cancel`,
  },
  JOBS: {
    LIST:       '/jobs',
    CREATE:     '/jobs',
    BY_NUMBER:  (jobNumber: string) => `/jobs/number/${jobNumber}`,
    BY_ID:      (id: string) => `/jobs/${id}`,
    HISTORY:    (id: string) => `/jobs/${id}/history`,
    TRANSITION: (id: string) => `/jobs/${id}/transition`,
  },
  QUOTES: {
    LIST:    '/quotes',
    CREATE:  '/quotes',
    BY_ID:   (id: string) => `/quotes/${id}`,
    APPROVE: (id: string) => `/quotes/${id}/approve`,
    REJECT:  (id: string) => `/quotes/${id}/reject`,
  },
  INVOICES: {
    LIST:   '/invoices',
    CREATE: '/invoices',
    BY_ID:  (id: string) => `/invoices/${id}`,
  },
  PAYMENTS: {
    LIST:       '/payments',
    INITIALIZE: '/payments/initialize',
    RECORD:     '/payments/record',
    BY_ID:      (id: string) => `/payments/${id}`,
  },
  TRACKING: {
    BY_NUMBER: (jobNumber: string) => `/tracking/${jobNumber}`,
  },
  DIAGNOSTICS: {
    CREATE:      '/diagnostics',
    BY_JOB:      (jobId: string) => `/diagnostics/job/${jobId}`,
    PHOTOS:      (id: string) => `/diagnostics/${id}/photos`,
    PHOTO_BY_ID: (id: string, photoId: string) => `/diagnostics/${id}/photos/${photoId}`,
  },
  NOTIFICATIONS: {
    LIST:          '/notifications',
    MARK_READ:     (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/mark-all-read',
  },
  BLOG: {
    LIST:       '/blog',
    CATEGORIES: '/blog/categories',
    CREATE:     '/blog',
    BY_SLUG:    (slug: string) => `/blog/${slug}`,
    BY_ID:      (id: string) => `/blog/${id}`,
  },
  FLEET: {
    LIST:     '/fleet',
    CREATE:   '/fleet',
    BY_ID:    (id: string) => `/fleet/${id}`,
    VEHICLES: (id: string) => `/fleet/${id}/vehicles`,
  },
  ANALYTICS: {
    DASHBOARD:   '/analytics/dashboard',
    REVENUE:     '/analytics/revenue',
    JOBS:        '/analytics/jobs',
    SERVICES:    '/analytics/services',
    TECHNICIANS: '/analytics/technicians',
  },
  UPLOADS: {
    PRESIGN: '/uploads/presign',
    CONFIRM: '/uploads/confirm',
  },
} as const;